service: hello-serverless

provider:
  name: aws
  runtime: nodejs12.x
  region: cn-northwest-1
  stage: dev
  memorySize: 256
  timeout: 10

functions:
  hello:
    handler: handler.hello
  add:
    handler: handler.add
    events:
      - http:
          path: math/add
          method: post
          cors: true
